version: '3.3'

services:
    # PHP-FPM
    app:
        image: php:8.0-fpm
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network

    # Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        ports:
            - 8000:80
        networks:
            - laravel-network
        depends_on:
            - app


    # MySQL
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

    # Mailhog
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
